name: Deploy Node.js App to Azure

on:
  push:
    branches:
      - azure
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out code
      - uses: actions/checkout@v4

      # 2) (Optional) Build front end, etc.
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # 3) Install server dependencies
      - name: Install Server Deps
        working-directory: ./server
        run: npm install

      # 4) Azure Login with Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: sp                # must be lowercase sp
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # 5) Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'YourWebAppName'
          package: './server'
