name: Build and deploy Node.js app to Azure Web App - hrapp

on:
  push:
    branches:
      - azure
  workflow_dispatch:

# IMPORTANT: permissions must be here (or on the *same* job that runs azure/login)
permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Example step that just does some install or build
      - name: Install & Build
        run: |
          npm install
          npm run build --if-present

      # OIDC-based login step
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # By not specifying client-secret, it defaults to OIDC
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_... }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_... }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_... }}
          # auth-type: 'oidc'  (optional to be explicit)

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hrapp'
          package: '.'
