name: Deploy Node.js App to Azure Web App

on:
  push:
    branches:
      - azure
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - uses: actions/checkout@v4

      # 2. Set up Node.js (using Node 20)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3. Build the frontend (Vite) so that the "dist" folder is created
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # 4. Install server dependencies
      - name: Install Server Dependencies
        working-directory: ./server
        run: npm install

      # 5. Login to Azure using service principal credentials
      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: sp
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # 6. Deploy the "server" folder to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'YourAzureWebAppName'
          slot-name: 'Production'
          package: './server'
