name: Build and deploy Node.js app to Azure Web App - hrsys

on:
  push:
    branches:
      - azure
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Build Frontend and Copy Dist
        run: |
          # Install and build frontend
          cd frontend
          npm install
          npm run build
          cd ..
          
          # Copy frontend/dist into server/dist
          mkdir -p server/dist
          cp -r frontend/dist/* server/dist/

      - name: Install Server Dependencies
        run: |
          cd server
          npm install

      - name: Upload Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: server/  # Upload the entire server directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download Server Artifact
        uses: actions/download-artifact@v4
        with:
          name: server
          path: server/  # Download into a "server" directory

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5CD1CE2A6C454AD4B95A8FDD0F3ED75F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A3D2E6D67B1944D5AD8041249BD263C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_772765EFE74F418FB0CA10C3EA84FB13 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hrsys'
          slot-name: 'Production'
          package: './server/'  # Deploy the downloaded server directory
